esphome:
  name: esp32c3
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32c3

esp32:
    board: esp32-c3-devkitm-1
    variant: esp32c3
    framework:
      type: esp-idf

logger:
    hardware_uart: USB_SERIAL_JTAG
    level: DEBUG # defaults to DEBUG, NONE ERROR WARN INFO DEBUG VERBOSE VERY_VERBOSE

# Example configuration entry
switch:
  - platform: gpio
    pin: GPIO1
    name: "StateLED"

# Example configuration entry
# Example configuration entry
sensor:
  - platform: adc
    pin: GPIO2
    name: "Analog"
    update_interval: 10s
    raw: true
    filters:
      - multiply: 0.0008058608 

# Enable Home Assistant API
api:
  encryption:
    key: "oeYxLH3uCJvBXkvE37eA/mH7I0gkd/MseEbXeQM9JPE="

ota:
  password: "a55b88e421491da5a99f610c4d547695"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32C3 Fallback Hotspot"
    password: "HuoB3DcHcmmS"

captive_portal:
    